feat: Add update_all function
nervosnetwork/sparse-merkle-tree pull request #18
Opened 2021-11-08 06:37 UTC by xxuejie

2021-11-12 06:29 UTC, TheWaWaR approved these changes

2021-11-13 09:20 UTC, jjyr approved these changes

2021-11-13 09:20 UTC, jjyr commented
@TheWaWaR Please release a new version with this PR. 😄

2021-11-14 11:15 UTC, quake requested changes

2021-11-14 11:15 UTC, quake commented on src/tree.rs
> +        leaves.dedup_by_key(|(a, _)| a.clone());
I think this fn is being used incorrectly, according to [doc](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.dedup_by_key)
```
Removes all but the first of consecutive elements in the vector that resolve to the same key.

If the vector is sorted, this removes all duplicates.

Examples
let mut vec = vec![10, 20, 21, 30, 20];

vec.dedup_by_key(|i| *i / 10);

assert_eq!(vec, [10, 20, 30, 20]);
```

we should first call `sort_by_key`, then call `dedup_by_key`

2021-11-15 07:39 UTC, merged